### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by weijia-cheng** [tkah/mary-wollstonecraft_a-vindication-of-the-rights-of-woman#1]
# General

- [x] Before doing anything else, you should update the toolset to the current version (2.7.1).
- [x] Rerun se clean.
- [x] Rebuild the table of contents.

# Meta

- [x] Editorial changes to citation of `Mr. Day’s “Sandford and Merton,” Volume 3` in f8ec9a78e8dd4dcbc4b76ca47a2edf63609af7dc need to be rebased out as we did with the Rosseau citations. Also, in any case Volume 3 should not be part of the title.
- [x] d573c27c00d26edad69fc10120e3b96fd8d05ff9 does not constitute an [Editorial] change since it is only changing semantics and presentation. Remove the editorial tag in a rebase.
- [x] 957e356d419c789396dcb88541f09d481e445609: Changing breaks to match the original scans is not editorial. Making a *conscious deviation* from the source material that potentially might change the meaning of the text is considered editorial.
- [x] 7f5858b1b668b20fb08edf8e567a03fda438e64f: Are these changes fixing issues with the transcription? If, so this commit should not be editorial. If, on the other hand, you made any changes that deviate from the book scans (i.e. fixing printer’s typos), they should be considered editorial (but the commit should be called “Fix printer’s typos” for clarity). If there is a mix of transcription fixes *and* printer’s typo fixes, we need to rebase the printer’s typo fixes out of this commit into a separate commit.

# Semantics

- [x] This book should be `z3998:non-fiction` throughout.
- [x] Blockquotes in the endnotes should not be considered epigraphs.
- [x] The dedication, being in letter form, can make use of [letter semantics and styling](https://standardebooks.org/manual/1.8.0/7-high-level-structural-patterns#7.7). Take a look at the [*Verses on Various Occasions*](https://github.com/standardebooks/john-henry-newman_verses-on-various-occasions/blob/master/src/epub/text/dedication.xhtml) dedication for some inspiration.
- [x] Subsections (as in chapters 5 and 13) should receive the `z3998:subchapter` semantic. Also, the actual text of the subsections need to be inside the `<section>` element, or else the section contains only the header, which is not semantically meaningful.
- [x] The italics on the author names and the `z3998:author` semantics in chapter-5 and the endnotes need to be removed.
- [x] In chapter-5, you have a sequence in which you unnecessarily applied an `<em>` to each individual word instead of the entire sequence (look for `Is not the following portrait`).
- [x] I don’t think that `Knox’s` in `Knox’s Essays` should be italicized.
- [x] `Rousseau’s <i epub:type="se:name.publication.book">Emilius</i>` inside note-5 should be in a `<cite>`.
- [x] note-11 should have the citation inside the same paragraph as the text.
- [x] note-18 should be a blockquote including both the paragraph and the citation.
- [x] Italics and semantics need to be added to some titles, e.g. `Miscellaneous pieces in Prose` and `Life of Johnson`.
- [x] We should add a period after the E in `Amy E Zelmer` (in both the colophon and the metadata) and add a `z3998:given-name` abbreviation semantic.

# Typography

- [x] In f8ec9a78e8dd4dcbc4b76ca47a2edf63609af7dc, you deleted some lines of asterisks, but those should have been replaced with thematic breaks (`<hr/>`s) rather than deleted outright.
- [x] Bridgeheads should be in sentence case. Also, the terminating periods can be restored.
- [x] In chapter-1, you missed converting an endnote (look for “best of men”).
- [x] Notes 30 and 35 should end in a period.

# Spelling

- [x] Accept changes made by `se modernize-spelling` (XIVth to XIV).
- [x] Lewis (as in Louis XIV) can be modernized to Louis.

# CSS

- [x] Update core.css and se.css to the versions included with 2.7.1.
- [x] Verse does not have the correct CSS. Per [the manual](https://standardebooks.org/manual/1.8.0/7-high-level-structural-patterns#7.5.8) this book should have:

```
[epub|type~="z3998:verse"] p{
	text-align: initial;
	text-indent: 0;
}

[epub|type~="z3998:verse"] p > span{
	display: block;
	padding-left: 1em;
	text-indent: -1em;
}

[epub|type~="z3998:verse"] p > span + br{
	display: none;
}
```

# Metadata

- [x] Short description needs to be a complete sentence (also, you have a typo in `philiosophy`).
- [x] Long description seems a little bare and vague, given the importance of this book. We should at least write a bit about the historical significance of this book as a work of feminist philosophy.

# Comments

- In future projects commits should be made more discrete, especially to prevent issues like mixing the editorial citation changes (which we did not want in the first place) with non-editorial changes moving footnotes to endnotes. c913ddab2c8df6ad94483d115a25fae2954cce41 is another example of a commit in which various changes are mixed (though no rebase is necessary for that case).

**Comment by weijia-cheng** [comment]
# General

- [x] I noticed that the original book has a subtitle, “With Strictures on Political and Moral Subjects,” which is missing here. Make sure to update the halftitlepage with the subtitle as well as the metadata. Lint will help you make changes everywhere they are necessary.

# Meta

- [x] c9c1219400c525f603b6e1baffa85809434b098d should be marked as an editorial commit. Modernizing spelling and hyphenation is always editorial.

# Semantics

- [x] With `Amy E. Zelmer` in the colophon, the `<b>` for the entire name should retain `z3998:personal-name`, but the `E.` initial needs an `<abbr>` tag with `z3998:given-name` (see [8.10.4.](https://standardebooks.org/manual/1.8.0/8-typography#8.10.4)).
- [x] `Mr. Day’s “Sandford and Merton,” Volume 3` needs to be in a `<cite>`. The title of the book should also be italicized with title semantics instead of quoted.
- [x] While `Knox’s` does not need to be italicized, `Essays` is still the title of a book and does need to be italicized with semantics.
- [x] The headers of the subchapters in chapters 5 and 13 should not receive the title semantic, or in fact any semantic at all. We should follow the [7.2.10.8](https://standardebooks.org/manual/1.8.0/7-high-level-structural-patterns#7.2.10.8) pattern and include the CSS rule (which should have the selector adjusted to `[epub|type~="z3998:subchapter"] header` to avoid conflicts with the letter CSS).
- [x] Rerun semanticate.

# Typography

- [x] In note-12, the backlink should not be in a separate paragraph.
- [x] Make sure to run typogrify after all other changes (it already makes some adjustments that we should include and the consequences of other changes may require more adjustments). Likewise with clean.

# Spelling

- [x] In an editorial commit, we can remove the gratituous capitalization of `Education` in note-35.

# CSS

- [x] For readability, we like to use comments like `/* Begin verse */` and `/* End verse */` to set apart groups of thematically related rules.

# Metadata

- [x] We don’t typically include the title in the short description—something like “Wollstonecraft argues that ...” would work.
